### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by Merith-TK** [TheMindVirus/CC-Modded#4]
1) Fix curseforge liscence to reflect the CC Lisence
2) rebase *all of this* as an actual, proper fork of CC:T,

**Comment by TheMindVirus** [comment]
1. What License?
2. Java, Scala, Gradle, GitPod and CurseForge have to do a lot better than they're currently doing at being "Open Source" for that to happen, so no. It is staying stable until such an event where that gets better. Proper forks don't work.

**Comment by Merith-TK** [comment]
1) https://github.com/TheMindVirus/CC-Modded/blob/main/LICENSE This one, 
2) actually making this an fork, means you can more easily integrate updates and features that are new from CC:T to CC:M

**Comment by Ocawesome101** [comment]
for what it's worth - copying CC code (particularly craftos) under a different license is technically illegal.  (though i see the LICENSE file does indeed contain the CCPL, which is good.)

> Java, Scala, Gradle, GitPod and CurseForge have to do a lot better than they're currently doing at being "Open Source" for that to happen, so no. It is staying stable until such an event where that gets better. Proper forks don't work.

can you please elaborate futher?

**Comment by TheMindVirus** [comment]
> for what it's worth - copying CC code (particularly craftos) under a different license is technically illegal. (though i see the LICENSE file does indeed contain the CCPL, which is good.)
> 
> > Java, Scala, Gradle, GitPod and CurseForge have to do a lot better than they're currently doing at being "Open Source" for that to happen, so no. It is staying stable until such an event where that gets better. Proper forks don't work.
> 
> can you please elaborate futher?

1. Java has gone from version 8 -> 17 and has brought as many compatibility fixes as everything else has become version hell
2. Scala actually half compiles without online dependencies now, but is a little redundant with languages like lua and python
3. Gradle has introduced build complexities the likes of which has only been out-worsened by cmake for C projects
4. GitPod has made cloud development a lot easier (and actually possible in most cases) but is not officially GitHub
5. CurseForge has overly harsh formatting rules in place (as well as the code linters) which limits mod releases too far

All of this leads to a broken modding platform that no one can bring themselves to use or reuse.
Be it for learning or by mistake, this has been the case for too long.

**Comment by Merith-TK** [comment]
1) already delt with in the main repo
2) why not contribute to the main repo if Scala is so much better?

3) cmake is not relevant, why bring it up

4) You have the gitpod functionality of this repo labeled as if it was your contribution when it infact was mine, stealing code and claiming it your own

5) curseforge yes, has harsh rules, but the code linters are put in place by Squid Dev, not curseforge, to make sure code is consistent across forks, so that one persons fork doesn't break five other forks, pre-commit either fixes these issues, or tells you where the issue is to fix before you actually commit to git,

**Comment by TheMindVirus** [comment]
Development for Development's sake is not the be all and end all. I question your definition of sharing.

**Comment by Ocawesome101** [comment]
What do you interpret here as "development for development's sake?"  Can you elaborate?

**Comment by TheMindVirus** [comment]
> What do you interpret here as "development for development's sake?" Can you elaborate?

This is when Developers or Engineers focus too much on the rules of the process to the point that it neglects or over-limits the freedoms of the final outcome. I refer in this context to the build process of CC, CraftOS, Minecraft Mods and Computer Hardware and Software in general.

**Comment by Ocawesome101** [comment]
when this means stealing others' work without credit, which you have, you've gone too far.

**Comment by TheMindVirus** [comment]
I would disagree with you there, I have credited CC:Tweaked where necessary. Development is impossible without an entry point.
Where would you like to start with the creditation? I'd like to thank the universe for existing without which I couldn't do anything.
To keep the work to yourself and accusing other people of stealing your idea? That's the stealing of ideas in itself.

**Comment by Merith-TK** [comment]
The main issue is that you are not using CCPL (as is legally required), and are not using an proper fork

Nothing is stopping you from making your own edits how you like on your own fork, just rebase your changes onto an proper fork, and don't change the liscence from CCPL unless you *explicitly get* dan200's approval,

I honestly couldnt give an shit about the changes you make, or if you use the linters or not, just keep it legal.

**Comment by TheMindVirus** [comment]
What you're calling "legal" is currently a grey minefield preventing all future work from taking place.
I am within my rights to make changes to my own version of the repository, of which you are unfairly criticising.
The changes will likely not work in what you call the "proper fork", let alone being applicable for a pull request.
Current compilation requires the use of GitPod and will not work on a local machine especially with no internet.
I suggest, to this "team of researchers" that seems to be ganging up on people for not being in a position to follow guidelines, that you reconsider your guiding principles and your bad language to which people without your privileges will find incredibly offensive.

**Comment by SquidDev** [comment]
@TheMindVirus: I think Merith is talking about the license on CurseForge - that does say MIT.

Everyone else: Guys, what this person has done is entirely legal, please stop harassing them.
